apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: smarbeidsgiver-pdfgen
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 70
  liveness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_alive
    timeout: 1
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  leaderElection: false
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 700Mi
  accessPolicy:
    inbound:
      rules:
        - application: syfosmaltinn
          namespace: teamsykmelding
          cluster: dev-gcp
